"from flask import Flask, render_template" 
"app = Flask(__name__)" 
"@app.route('/')" 
"def home():" 
"    return render_template('index.html')" 
"if __name__ == '__main__':" 
"    app.run(debug=True)" 
"from flask_migrate import Migrate" 
"migrate = Migrate(app, db)" 
"import logging" 
"@app.errorhandler(404)" 
"def not_found(e):" 
"    return render_template('404.html'), 404" 
"logging.basicConfig(filename='app.log', level=logging.ERROR)" 
