"from flask import Blueprint, request" 
"coupons = Blueprint('coupons', __name__)" 
"@coupons.route('/coupons')" 
"def list_coupons():" 
"    coupons = get_coupons()" 
"    return render_template('coupons.html', coupons=coupons)" 
